### PR TITLE
Container-based workflow

### PR DESCRIPTION
**Pull request by jharmison-redhat**
Adds alternative run script, more documentation, and a Dockerfile for packaging and running container images on the fly.

Very little security added, this just effectively isolates the runtime environment to a known-good environment on execution, intended to add portability to the environment. It's little more than a quick hack, but should work well for local development.

Tested working on Fedora here, would like two sets of eyes on it if I can get them. Another Linux user of some sort, and a Mac user. If you can test this please let me know and I'll assign you as a reviewer.

### CODE REVIEW

**Comment by jharmison-redhat** [comment]
Note: Documentation for usage is here:
https://github.com/jharmison-redhat/openshift-devsecops/tree/dockerfile#alternative-container-based-usage

**Comment by jharmison-redhat** [comment]
image

**Comment by jharmison-redhat** [comment]
image

**Comment by jharmison-redhat** [comment]
@mbach04 I added you to the repo so you can be marked as a reviewer - I would appreciate a quick run against an RHPDS cluster on your end using this workflow if you could. Tyvm!

**Comment by mbach04** [comment]
I like this approach. As soon as I scrub the current cluster I'll spin up a new one using this PR.

**Comment by jharmison-redhat** [comment]
e5e99d9 Worked to get Jay running on Mac OS afaik

9ff0845 gives us log persistence/retrieval between runs

**Comment by jflowers** [comment]
LGTM, @jharmison-redhat you are the best!

**Comment by jharmison-redhat** [comment]
@jflowers if you wouldn't mind looking over the small code changes and running at least the `test` playbook with an empty `tmp` directory (no cluster required), I would appreciate it.

I should have corrected the following workflow problems:
- Variables with unclear comments and hard prereqs for `run-container.sh` have been set to just fix themselves via hack
- Everything is better commented now and hopefully easier to follow
- The kubeconfig logic tweak I mentioned to you should work fine
  - If you specify a kubeconfig, it will copy it every time
  - If you don't specify a kubeconfig, but one has been copied or created before, it will silently continue
  - If you don't specify a kubeconfig, but are provisioning a fresh cluster it noops because one will be created
  - If you don't specify a kubeconfig, and aren't provisioning, but one is in the default location, it will warn you that it's just using that and will copy it the first time you run the script (but not overwrite it later)
  - If you don't specify a kubeconfig, aren't provisioning, and don't have a default one created already, it will error and quit
- Failing to pass or export a required variable (export DEVSECOPS_CLUSTER=<x> or --cluster=<x>) now quits the script, instead of spitting an error message and keeping on keeping on

**Comment by jharmison-redhat** [comment]
Rebased on master

**Comment by jharmison-redhat** [comment]
Since this doesn't change anything regarding normal runs, does enable new behavior, I've just redeployed it from this rebased state, and I haven't heard any further negative feedback, I'm going to go ahead and merge this.

**Pull request merged**
