### PR TITLE
Implement Workshop spawner and dashboard (openshift homeroom)

### PR DESCRIPTION
**Pull request by andykrohg**
#5 adding openshift-homeroom role => more appropriately named workshop-spawner

The documentation will need further review, particularly to address user-specific variable interpolation and the refactored workshop architecture, but wanted to get this in so you could take a look.

image

### CODE REVIEW

**Comment by andykrohg** [comment]
Pushed some changes because I realized I was including some unnecessary content. PR is ready for review

**Comment by jharmison-redhat** [comment]
There are some problems I'm cleaning up right now, I'll include patches once I get them fixed.

**Comment by jharmison-redhat** [comment]
The following fixes some route specification problems, additionally there were some OperatorGroup conflicts with CRW that I patched in master. I would rebase your branch off of current master for testing on your own end.

Right now the workshop-spawner is still not coming up, I'm looking into that still.

``` diff
diff --git a/roles/devsecops/defaults/main.yml b/roles/devsecops/defaults/main.yml
index cea514c..14b6b2e 100644
--- a/roles/devsecops/defaults/main.yml
+++ b/roles/devsecops/defaults/main.yml
@@ -8,5 +8,6 @@ deploy_nexus: true
 deploy_3scale: true
 deploy_crw: true
 deploy_pipeline: true
+deploy_workshop: true
 
 pipeline_style: tekton
diff --git a/roles/devsecops/tasks/main.yml b/roles/devsecops/tasks/main.yml
index a28e452..c8d4e2b 100644
--- a/roles/devsecops/tasks/main.yml
+++ b/roles/devsecops/tasks/main.yml
@@ -38,3 +38,6 @@
   when:
     - deploy_pipeline
     - pipeline_style == 'jenkins'
+- include_role:
+    name: workshop-spawner
+  when: deploy_workshop
diff --git a/roles/workshop-spawner/tasks/main.yml b/roles/workshop-spawner/tasks/main.yml
index c49d98b..413440c 100644
--- a/roles/workshop-spawner/tasks/main.yml
+++ b/roles/workshop-spawner/tasks/main.yml
@@ -13,7 +13,7 @@
 
 - name: Wait for KeyCloak to respond to requests
   uri:
-    url: 'https://keycloak-{{ crw_project_name }}.{{ openshift_base_domain }}/'
+    url: 'https://keycloak-{{ crw_project_name }}.apps.{{ cluster_name }}.{{ openshift_base_domain }}/'
     return_content: yes
     validate_certs: no
   register: keycloak_endpoint
@@ -28,10 +28,10 @@
 
 - name: Wait for the Spawner to respond to requests
   uri:
-    url: 'https://dashboard.{{ openshift_base_domain }}/'
+    url: 'https://dashboard.apps.{{ cluster_name }}.{{ openshift_base_domain }}/'
     return_content: yes
     validate_certs: no
   register: dashboard_endpoint
   until: dashboard_endpoint.status == 200
   retries: 20
-  delay: 5
\ No newline at end of file
+  delay: 5
diff --git a/roles/workshop-spawner/templates/workshop-spawner.yml.j2 b/roles/workshop-spawner/templates/workshop-spawner.yml.j2
index 1156ef9..a104797 100644
--- a/roles/workshop-spawner/templates/workshop-spawner.yml.j2
+++ b/roles/workshop-spawner/templates/workshop-spawner.yml.j2
@@ -388,7 +388,7 @@ items:
     name: external-keycloak-spawner
     namespace: {{ workshop_spawner_project_name }}
   spec:
-    host: dashboard.{{ openshift_base_domain }}
+    host: dashboard.apps.{{ cluster_name }}.{{ openshift_base_domain }}
     port:
       targetPort: 8080-tcp
     tls:
@@ -416,4 +416,4 @@ items:
         name: {{ workshop_dashboard_image }}
       name: latest
 kind: List
-metadata: {}
\ No newline at end of file
+metadata: {}
```

**Comment by jharmison-redhat** [comment]
> Invalid parameter: redirect_uri

Error I get from Keycloak when trying to access the dashboard.

**Comment by jharmison-redhat** [comment]
> [I 2020-04-16 14:05:32.132 JupyterHub log:174] 302 GET / -> /hub/ (@::ffff:10.128.2.19) 0.81ms
> [I 2020-04-16 14:05:32.302 JupyterHub log:174] 302 GET /hub/ -> /hub/login (@::ffff:10.131.0.20) 0.76ms
> [I 2020-04-16 14:05:32.454 JupyterHub log:174] 302 GET /hub/login -> /hub/oauth_login (@::ffff:10.128.2.19) 0.69ms
> [I 2020-04-16 14:05:32.608 JupyterHub oauth2:100] OAuth redirect: 'https://dashboard.apps.openshift.jharmison.net/hub/oauth_callback'
> [I 2020-04-16 14:05:32.609 JupyterHub log:174] 302 GET /hub/oauth_login -> https://keycloak-devsecops.apps.openshift.jharmison.net/auth/realms/codeready/protocol/openid-connect/auth?response_type=code&redirect_uri=https%3A%2F%2Fdashboard.apps.openshift.jharmison.net%2Fhub%2Foauth_callback&client_id=codeready-public&state=[secret] (@::ffff:10.131.0.20) 1.20ms

Logs from external-keycloak-spawner pod

**Comment by jharmison-redhat** [comment]
> [0m[33m14:22:11,114 WARN  [org.keycloak.events] (default task-1) type=LOGIN_ERROR, realmId=804ba782-8b2c-4040-b641-1338f8c82dcd, clientId=codeready-public, userId=null, ipAddress=24.236.81.56, error=invalid_redirect_uri, redirect_uri=https://dashboard.apps.openshift.jharmison.net/hub/oauth_callback

Logs from keycloak

**Comment by jharmison-redhat** [comment]
CRW comes up fine, am able to log in no problem.

**Comment by jharmison-redhat** [comment]
Manually rebased to remove excess merge commits. LGTM, closing.

**Pull request closed without merging**
